sudo: false

language: python

python:
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - flake8 src test --ignore=E501,E731
  - coverage run --source=contexts -m contexts -v
  - pushd doc && make html && popd

after_success:
  coveralls

