sudo: false

language: python

matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
    sudo: required
    dist: xenial
  - python: 3.6
    env: TOX_ENV=flake8
  - python: 3.6
    env: TOX_ENV=coverage
  - python: 3.6
    env: TOX_ENV=docs

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
  - "$HOME/.cache/pip"
